version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - waha-data:/app/data
    environment:
      - NODE_ENV=production
    networks:
      - waha-network

volumes:
  waha-data:
    driver: local

networks:
  waha-network:
    driver: bridge 